source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def pods
    pod 'Alamofire', '~> 3.0'
    pod 'Cartography', '~> 0.6.0'
    pod 'SwiftyJSON', '~> 2.3.2'
    pod 'SVProgressHUD', '~> 2.0'
    pod 'SDCycleScrollView', '~> 1.64'
    pod 'PNChart', '~> 0.8.8'
    pod 'SlideMenuControllerSwift'
    pod 'Kingfisher'
    pod 'JLToast'
    pod 'Wilddog'
    
end

target 'Hypnos' do
    pods
end